# Generated by Django 4.2.1 on 2023-06-14 07:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='CV(PNG/JPEG)')),
                ('date_applied', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_cv', to='career_auth.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('job_location', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('remote', 'remote'), ('part-time', 'part-time'), ('full-time', 'full-time'), ('negotiations', 'negotiations')], max_length=200)),
                ('position', models.CharField(choices=[('junior', 'junior'), ('intermediate', 'intermediate'), ('senior', 'senior'), ('expart', 'expart')], max_length=200)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='career_auth.employer')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='career_job.category')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='career_job.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='career_job.job')),
            ],
        ),
    ]
